### ISSUE TITLE
To-do 1.2

### ISSUE THREAD

**Issue by BondaCB** [gsabater/Mediavida-Notifier#2]
### To do
- [ ] Unificar los estilos de "nueva macro" en oscuro y claro.
- [ ] Capturar enlaces de twitter como los de mediavida (mvn.embed)
- [ ] Las macros no funcionan en live
- [ ] Opción para eliminar el botón de citar
- [ ] Opción para mover el botón de citar al bottom del post.
- [x] Los álbumes de imgur se detectan mal.
- [x] las url de youtube con 'channel' no deberian trackear
- [x] Añadir: `text-decoration: inherit` a  `.mvn-tooltip, .mvn-embed-highlight {`
- [x] Al editar un post, sale la barra de MV Usertools
- [x] Al mandar un PM, aparece el redactor.
- [x] Arreglar undefined en el redactor para los separators
- [x] Bug de tamaños dropzone al editar post en formulario avanzado
- [x] Bug al cargar un hilo con el [OP banned](https://www.mediavida.com/foro/off-topic/escritorios-enero-2016-551113/3), [ejemplo # 1](http://www.mediavida.com/foro/moviles-tablets/nvidia-shield-tablet-527239)
- [x] Bug al pulsar la tecla intro para guardar una macro
- [x] Capturar enlaces de humblebundle como los de mediavida (mvn.embed)
- [x] Get enlace de las imagenes mvn-lightbox y si tienen href, eliminar el mvn-lightbox
- [x] Al desplegar los emoticonos, se montan sobre el texto
- [x] Bug al detectar un perfil de instagram como embed.

---
### Quizás
- ¿Crear una página de Github para la extensión?
- [ ] Arreglar la página de Github y # 1 en el post
- [x] [Al abrir un vídeo, lleva al final de la página](https://imgflip.com/readImage?iid=40595741) (Opción para desactivar scroll al cargar en el lightbox?)

---
### No es posible
- [x] Capturar enlaces de github como los de mediavida (mvn.embed), con el icono de github.
- [x] Capturar enlaces de facebook como los de mediavida (mvn.embed)
- [x] Capturar enlaces de steam como los de mediavida (mvn.embed)
- `*No es posible debido a que GitHub, facebook y steam no permiten x-origin: iframe.*`
- [x] Al arrastrar texto, se activa el panel de drag and drop.
- `*No es posible ya que datatransfer no está disponible en el evento dragevent. Lo esta en dragstart*`
