### ISSUE TITLE
Sugerencias de la comunidad

### ISSUE THREAD

**Issue by BondaCB** [gsabater/Mediavida-Notifier#3]
- [ ] Un enlace permanente al post en la fecha
- [ ] Convertir en live cualquier hilo (idea de MV-usertools)
- [ ] Botón para abrir todos los mensajes no leídos de los hilos en favoritos (1101)
- [ ] Poder añadir un post a marcadores. ( 826 827)
- [ ] Un ajuste para recibir solamente avisos de grupos. Y no de todos los avisos.
- [ ] [Ordenar posts por "polémicos". El que más quoteos tenga el primero y así.](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/9#246)
- [ ] [Intentar reestablecer las cookies de spy en la extension](http://www.mediavida.com/foro/mediavida/sugerencias-para-proxima-mediavida-463408/41#1221)
- [ ] [Webextensions para firefox](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/19#552)
- [ ] [Añadir un nuevo botón en el redactor para la macro de shop ](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/25#750)
- [ ] [Un botón para abrir la galería de imagenes, y un masonry overview del hilo](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/26#769)
- [ ] [Ordenar los hilos estilo reddit, por conversaciones.](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/26#773)
- [ ] [MV SFW](http://www.mediavida.com/foro/mediavida/modo-trabajo-543006)
- [ ] [Browseraction dinámico](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/26#780)
- [ ] Rescatar la funcionalidad de foros favoritos de la MV Usertools
- [ ] [marcar como leido cuando estás en live](http://www.mediavida.com/foro/mediavida/sugerencias-para-proxima-mediavida-463408/40#1171)
- [ ] [Invertir orden de los post](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/27#801)
- [ ] [Modo "lite", sin imagenes ni videos, para los hilos live](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/28#832)
- [ ] Cargar página anterior dinámicamente on click.
- [ ] [Streaming más grande en hilos live](http://www.mediavida.com/foro/mediavida/mediavida-notifier-chrome-extension-541508/29#856)

---
- [x] Que los posts borrados no aparezcan, en vez de "post eliminado"
- [x] Flechas para el lightbox para las imagenes de un mismo post.
